export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USERS = "GET_USERS";
export const ITEM_LOADING = "ITEM_LOADING";
export const SET_CURRENT_ITEM = "SET_CURRENT_ITEM";
export const GET_ITEMS = "GET_ITEMS";
export const TRANSACTION_LOADING = "ITEM_LOADING";
export const SET_CURRENT_TRANSACTION = "SET_CURRENT_ITEM";
export const GET_TRANSACTIONS = "GET_ITEMS";

